### ISSUE TITLE
Sensor unavailable

### ISSUE THREAD

**Issue by phoenix-blue** [snowienator/Home-Assistant-Prijsplafond#1]
Hi,

I have setup this inside hacs and insert the config to the sensor.yaml (changed the utility sensors to my own sensors)

I see now the sensor.prijsplafond_gas and stroom
But the other sensors are unavailable, is this an matter of time they are working?

**Comment by pluim003** [comment]
I have also only sensor.prijsplafond_gas and stroom which then gives me the total of the current month.
How did you set it up through Hacs? I couldn't find it there. Just copied the stuff manually.

**Comment by snowienator** [comment]
Hi guys,

@phoenix-blue this integration provides 2 sensors, one for gas consumption and the other for power, or as we in Dutch say stroom. All data like cap, what it costs at this time can be found as attribute of the specific entity. See screenshot as example. 
![355600A4-BB5E-4368-B76E-0A3BFFCF0C24](https://user-images.githubusercontent.com/688313/211557402-95f8c01e-9c47-4d10-b919-281e9e804e04.png)

@pluim003 
I’m still working on the procedure to add this integration in HACS by default. Currently the only installation option is to add this repo in HACS under the custom repo option on the integration page. Will work on this when I get back from holiday.

Does this help you both?

**Comment by pluim003** [comment]
Aha, thanx. I missed the attributes part. And I'll check the custom repo option later. Could the monthly fixed numbers be added in one way or another to the energy dashboard?
And should solar-panel-export not be taken into account? As my total electricity-consumption will be based also on what I return to the net. Or should the export-entities be added to the prijsplafond-sensor with the minus-sign? During the summer months I'll return usually more to the net then I get from it.

Enjoy your holiday.

**Comment by snowienator** [comment]
Great ideas, will look into when I get back.

**Comment by phoenix-blue** [comment]
> Hi guys,
> 
> @phoenix-blue this integration provides 2 sensors, one for gas consumption and the other for power, or as we in Dutch say stroom. All data like cap, what it costs at this time can be found as attribute of the specific entity. See screenshot as example. ![355600A4-BB5E-4368-B76E-0A3BFFCF0C24](https://user-images.githubusercontent.com/688313/211557402-95f8c01e-9c47-4d10-b919-281e9e804e04.png)
> 
> @pluim003 I’m still working on the procedure to add this integration in HACS by default. Currently the only installation option is to add this repo in HACS under the custom repo option on the integration page. Will work on this when I get back from holiday.
> 
> Does this help you both?

Yes, i see the missing part .
Is it possible to show the rest amount of kWh in place of the used kWh?

**Comment by snowienator** [comment]
Yes that’s possible. You can use the template sensor to do the monthly cap - the current entity state. Do you need an example for this?

**Comment by pluim003** [comment]
Might be nice because I haven't found out where the cap-value comes from (or at least somewhere from the code (in const.py)) but my python-knowledge isn't that great (yet).

**Comment by snowienator** [comment]
Added template sensor example in README
