### ISSUE TITLE
Prijsplafond values get off during short downtime for backup

### ISSUE THREAD

**Issue by pluim003** [snowienator/Home-Assistant-Prijsplafond#2]
I notice the following:

![afbeelding](https://user-images.githubusercontent.com/67138922/212748138-54b3ab5b-59fd-4731-b962-b8a8a5ef7aa3.png)

Same for gas. Currently this month about 114kWh has been used.
What happens at 3AM? A cronjob stops the HomeAssistant-container to backup the data-directory. 

My workaround will be to skip this backup. I also make a backup with open files which I fortunately hadn't to restore (as well as the regular backup). Wondering what can cause this...

**Comment by snowienator** [comment]
When HA restarts the sensor state gets reset to 0.. Then when the sensor reaches his update period it restores to a correct value using the given sources. That's causes this weird line in your graph.

Until last week I didn't find a way to overcome those drops in the graph. But now I do.. Planning to fix this in the next release planned for this weekend.

You should under no circumstance skip the backup..

**Comment by pluim003** [comment]
Aha, great. That explains a lot. Well I make backups with open HASS-database. And as during those times not much happens then I'm not too worried of losing lots of data. Maybe pausing the dockercontainer might be sufficient. I'll give that a try. And ofcourse waiting for the next release. Thanx.

But weird was that it will after the drop also stay lower than the value before the restart. Which causes the values be quite off of the real usage. Well not too much of a problem because I've about used one third of the Prijsplafond-values and the months is over half over. As long as it won't be -10 degrees we should be 'safe'. :-)

**Comment by pluim003** [comment]
Can confirm that pausing the container during the backup gives better results.

**Comment by snowienator** [comment]
You will also experience the 'drop' after an update though.. So you will get it eventually

**Comment by snowienator** [comment]
Fixed issue in latest release.
