### ISSUE TITLE
Adding integration directly

### ISSUE THREAD

**Issue by pluim003** [snowienator/Home-Assistant-Prijsplafond#5]
When I add the integration directly I'm prompted to enter the entities to be used for prijsplafond but the one for gas can't be chosen:

![afbeelding](https://user-images.githubusercontent.com/67138922/214045150-94224434-f9e2-4717-9b3b-1d71dfead29e.png)

The screenshot doesn't contain more entities to choose from but gas is missing.

This is causing that my gas usage for the months is now set to 0.

**Comment by snowienator** [comment]
On initial configuration you see 3 entity listings. The first one is for energy consumers, then second for energy producers (solar panels) and the third one is for gas consumers.
![image](https://user-images.githubusercontent.com/688313/214048263-e3219471-936c-4ce5-9e11-728f280ec8ef.png)

I haven't yet found out why my data descriptors are not working with the entity listings. I've also marked this a bug in my release.

**Comment by pluim003** [comment]
Aha, that made sense, so started with the 3rd one and added there the Gas, then started with the first which gave me some extra's then. So I hadn't looked that good. Seems to be working now and I have a value for gas again. Well everything is slightly off due to another restart before re-adding the integration. 

Would it be convenient to get the values somehow from the ones used in the energy dashboard? Although I don't know where those values are being stored:

![afbeelding](https://user-images.githubusercontent.com/67138922/214066351-1fb0b37c-879c-4f8b-9ce7-0ec029da6bda.png)

**Comment by snowienator** [comment]
Sadly there is no way of customization in the energy dashboard.. Yet I hope.. 
If you are looking for the data. This can be found on Developer Tools > Statistics.

What you mean with slightly off? The integration fetches the provided entities from the history plugin, lets say the first recorded state of this month) and then calculcates the usage untill now. So it should not matter whether you start now or later.

**Comment by pluim003** [comment]
There were issues after a restart when there was a dip in the prijsplafond-values. Above here in the screenshot are the real values of usage this month, whereas the prijsplafond-values (see the screenshot in https://github.com/rbrink/Home-Assistant-Prijsplafond/issues/6 gives other values up till today. As it seems we will stay below the caps for this month it won't bother (and otherwise there was nothing to do about it except for turning the heating a few degrees lower, but then the mrs won't like it :-) ). Let's see how February will do.

**Comment by snowienator** [comment]
I looked closer to your energydistribution thingy and see your values are way different than as shown in #6.. Kind of shocked actually..

My data is like the same..
<img width="997" alt="image" src="https://user-images.githubusercontent.com/688313/214116091-c2664415-8f66-4d18-b220-1a09801325fe.png">
The only diff I have is with the consumed energy, but I found out that is because I calculate with all the decimals and hassio Energy removes some.. So this might be a rounding thingy..

**Comment by pluim003** [comment]
That's indeed quite close. I must say I didn't start at Jan 1st but I think in the beginning it was almost the same but after the nightly restarts (for the backup) it got off.

Before the update of Docker arond 7AM on RPi4 it wat at 120 m3 for gas:

![afbeelding](https://user-images.githubusercontent.com/67138922/214141474-e53a2aa0-de60-481a-9b7f-210d60c084fd.png)

**Comment by pluim003** [comment]
Last night again a weird drop:

![afbeelding](https://user-images.githubusercontent.com/67138922/214233462-71b965c9-fb56-4725-963c-2dab3a0698b6.png)

Nothing special going on at 4AM which can cause this. Same for gas.

Should I start a new issue?

**Comment by snowienator** [comment]
Hmm.. i'll start a new issue for this.

**Comment by snowienator** [comment]
@pluim003 can you share the historic data from your source sensors somewhat before the drop and afterwards in #7 ?

**Comment by snowienator** [comment]
Closes in latest release
