### ISSUE TITLE
Plafond "Power" Error

### ISSUE THREAD

**Issue by Alfagek** [snowienator/Home-Assistant-Prijsplafond#9]
Only the power fails over here. Gas is working.

Using dsmr.month.merged sensor or using dsmr.month.low and dsmr.month.high sensors.
All the 3 sensors are visible in HA. And outout is kWh.

I do get the next error:

Logger: homeassistant.helpers.entity
Source: custom_components/prijsplafond/sensor.py:194
Integration: Prijsplafond ([documentation](https://github.com/rbrink/Home-Assistant-Prijsplafond), [issues](https://github.com/rbrink/Home-Assistant-Prijsplafond/issues))
First occurred: 16:37:32 (2 occurrences)
Last logged: 16:43:02

Update for sensor.prijsplafond_power fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_device_update
    raise exc
  File "/config/custom_components/prijsplafond/sensor.py", line 172, in async_update
    pos_usage += await self._get_value(entity_id)
  File "/config/custom_components/prijsplafond/sensor.py", line 194, in _get_value
    usage = float(state_old.state)
ValueError: could not convert string to float: 'unknown'

**Comment by snowienator** [comment]
You are just before me.. Have fixed this in the next release. Will push it through now.

**Comment by Alfagek** [comment]
> 

@rbrink Awesome 😎👍🏻

**Comment by snowienator** [comment]
@Alfagek, new release has been published. Could you check if your sensor loads without any issues now?

**Comment by Alfagek** [comment]
![510FD3B9-75DB-4019-8677-20768BFD0F97](https://user-images.githubusercontent.com/76258622/215346325-a83f8fec-fa41-4bd3-97aa-a7cb0f56e22b.jpeg)
@rbrink, Working 👌🏻

only thing I’m “missing” is a separate sensor for the power cap like the gas cap. But you can see that at the power sensor

**Comment by Alfagek** [comment]
Was a bit to quick to say it’s working 🤗. It is working, but have now still a warning in the HA log. For usage and return. 

Logger: custom_components.prijsplafond.const.const
Source: custom_components/prijsplafond/sensor.py:172 
Integration: Prijsplafond ([documentation](https://github.com/rbrink/Home-Assistant-Prijsplafond), [issues](https://github.com/rbrink/Home-Assistant-Prijsplafond/issues)) 
First occurred: 29 januari 2023 om 19:01:18 (304 occurrences) 
Last logged: 07:36:23

Unable to convert the first recorded state of this month for: sensor.dsmr_current_month_electricity2 to float..Value is: unknown. Setting usage to 0.
Unable to convert the first recorded state of this month for: sensor.dsmr_current_month_electricity1 to float..Value is: unknown. Setting usage to 0

**Comment by snowienator** [comment]
What does the data of sensor.dsmr_current_month_electricity2 look like? Hassio often assigns the state unknown to sensors which are slowly initialized. As Unknown is not numeric I cannot do a calculation with it.. Therefor assuming it's set to 0. Will write an update this week to fix this.

**Comment by Alfagek** [comment]
Its giving the normal numbers. So that is strange.
![image](https://user-images.githubusercontent.com/76258622/215486646-d0f45582-2be8-4537-be63-0a1209f5e14b.png)

But it could be the problem what is called in #7 . 
My database is also getting purged after 14days.
Lets close this topic, en move a head with this strange problem at #7
